/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CoreOutput
 */
export interface CoreOutput {
    /**
     * 
     * @type {string}
     * @memberof CoreOutput
     */
    'error'?: string;
    /**
     * 
     * @type {string}
     * @memberof CoreOutput
     */
    'target'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CoreOutput
     */
    'success': boolean;
}

