/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TagNameInputDto } from './tag-name-input-dto';

/**
 * 
 * @export
 * @interface CreateMemoInputDto
 */
export interface CreateMemoInputDto {
    /**
     * 
     * @type {number}
     * @memberof CreateMemoInputDto
     */
    'cateId': number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMemoInputDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateMemoInputDto
     */
    'content': string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMemoInputDto
     */
    'important': boolean;
    /**
     * 
     * @type {Array<TagNameInputDto>}
     * @memberof CreateMemoInputDto
     */
    'tags'?: Array<TagNameInputDto>;
}

