/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Tags } from './tags';

/**
 * 
 * @export
 * @interface Memos
 */
export interface Memos {
    /**
     * 
     * @type {number}
     * @memberof Memos
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Memos
     */
    'createAt': string;
    /**
     * 
     * @type {string}
     * @memberof Memos
     */
    'updateAt': string;
    /**
     * 
     * @type {string}
     * @memberof Memos
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Memos
     */
    'content'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Memos
     */
    'important': boolean;
    /**
     * 
     * @type {number}
     * @memberof Memos
     */
    'userId': number;
    /**
     * 
     * @type {number}
     * @memberof Memos
     */
    'cateId': number | null;
    /**
     * 
     * @type {Array<Tags>}
     * @memberof Memos
     */
    'tag': Array<Tags>;
}

