/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Categories } from './categories';
// May contain unused imports in some cases
// @ts-ignore
import { Memos } from './memos';
// May contain unused imports in some cases
// @ts-ignore
import { Tags } from './tags';

/**
 * 
 * @export
 * @interface SendContentDataOutputDto
 */
export interface SendContentDataOutputDto {
    /**
     * 
     * @type {string}
     * @memberof SendContentDataOutputDto
     */
    'error'?: string;
    /**
     * 
     * @type {string}
     * @memberof SendContentDataOutputDto
     */
    'target'?: string;
    /**
     * 
     * @type {string}
     * @memberof SendContentDataOutputDto
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SendContentDataOutputDto
     */
    'success': boolean;
    /**
     * 
     * @type {Categories}
     * @memberof SendContentDataOutputDto
     */
    'cate'?: Categories;
    /**
     * 
     * @type {Memos}
     * @memberof SendContentDataOutputDto
     */
    'memos'?: Memos;
    /**
     * 
     * @type {Tags}
     * @memberof SendContentDataOutputDto
     */
    'tags'?: Tags;
}

