/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateAccountDto
 */
export interface UpdateAccountDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountDto
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountDto
     */
    'mobile': string;
}

