/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CateInputDto } from './cate-input-dto';

/**
 * 
 * @export
 * @interface UpdateManyCateInputDto
 */
export interface UpdateManyCateInputDto {
    /**
     * 
     * @type {Array<CateInputDto>}
     * @memberof UpdateManyCateInputDto
     */
    'data': Array<CateInputDto>;
}

