/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Categories } from './categories';
// May contain unused imports in some cases
// @ts-ignore
import { Memos } from './memos';
// May contain unused imports in some cases
// @ts-ignore
import { Tags } from './tags';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'updateAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'mobile': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'refreshToken'?: string;
    /**
     * 
     * @type {Array<Categories>}
     * @memberof User
     */
    'cate': Array<Categories>;
    /**
     * 
     * @type {Array<Memos>}
     * @memberof User
     */
    'memos': Array<Memos>;
    /**
     * 
     * @type {Array<Tags>}
     * @memberof User
     */
    'tags': Array<Tags>;
}

