openapi: 3.0.0
paths:
  /user/all:
    get:
      operationId: getAll
      parameters: []
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
      tags:
        - User
  /user/register:
    post:
      operationId: createAccount
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAccountDto"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - User
  /user/modify:
    patch:
      operationId: profileUpdate
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAccountDto"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - User
  /user/profile:
    get:
      operationId: profile
      parameters: []
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      tags:
        - User
  "/user/{id}":
    delete:
      operationId: delete
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - User
  /user/testApi:
    post:
      operationId: testApi
      parameters: []
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - User
  /auth/login:
    post:
      operationId: login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginOutput"
      tags:
        - Auth
  /auth/refresh:
    get:
      operationId: refreshToken
      parameters: []
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenOutput"
      tags:
        - Auth
  /auth/logout:
    get:
      operationId: logout
      parameters: []
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - Auth
  /memo/createMemo:
    post:
      operationId: createMemo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMemoInputDto"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - Memo
  /memo/createCate:
    post:
      operationId: createCate
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCateDto"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateCateOutputDto"
      tags:
        - Memo
  /memo/sendContentData:
    post:
      operationId: sendContentData
      parameters: []
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendContentDataOutputDto"
      tags:
        - Memo
  /memo/updateOneCate:
    post:
      operationId: updateOneCate
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CateInputDto"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - Memo
  /memo/updateManyCate:
    post:
      operationId: updateManyCate
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateManyCateInputDto"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - Memo
  /memo:
    delete:
      operationId: deleteCate
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CateIdInputDto"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoreOutput"
      tags:
        - Memo
  /openAi/createCompletion:
    post:
      operationId: createCompletion
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCompletionInputDto"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Promise"
      tags:
        - OpenAi
info:
  title: My API
  description: An API to do awesome things
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    Promise:
      type: object
      properties: {}
    Tags:
      type: object
      properties:
        id:
          type: number
        createAt:
          format: date-time
          type: string
        updateAt:
          format: date-time
          type: string
        tagName:
          type: string
        user:
          $ref: "#/components/schemas/Promise"
        memos:
          $ref: "#/components/schemas/Promise"
        memoId:
          type: number
        cate:
          $ref: "#/components/schemas/Promise"
        cateId:
          type: number
      required:
        - id
        - createAt
        - updateAt
        - tagName
        - user
        - memos
        - memoId
        - cate
        - cateId
    Memos:
      type: object
      properties:
        id:
          type: number
        createAt:
          format: date-time
          type: string
        updateAt:
          format: date-time
          type: string
        title:
          type: string
        content:
          type: string
        important:
          type: boolean
        user:
          $ref: "#/components/schemas/Promise"
        cate:
          nullable: true
          allOf:
            - $ref: "#/components/schemas/Promise"
        cateId:
          type: number
          nullable: true
        tags:
          $ref: "#/components/schemas/Tags"
      required:
        - id
        - createAt
        - updateAt
        - important
        - user
        - cate
        - cateId
        - tags
    Categories:
      type: object
      properties:
        id:
          type: number
        createAt:
          format: date-time
          type: string
        updateAt:
          format: date-time
          type: string
        cateName:
          type: string
          nullable: true
        user:
          $ref: "#/components/schemas/Promise"
        memos:
          $ref: "#/components/schemas/Memos"
        tags:
          $ref: "#/components/schemas/Tags"
      required:
        - id
        - createAt
        - updateAt
        - cateName
        - user
        - memos
        - tags
    User:
      type: object
      properties:
        id:
          type: number
        createAt:
          format: date-time
          type: string
        updateAt:
          format: date-time
          type: string
        email:
          type: string
        password:
          type: string
        name:
          type: string
        mobile:
          type: string
        refreshToken:
          type: string
        cate:
          $ref: "#/components/schemas/Categories"
        memos:
          $ref: "#/components/schemas/Memos"
        tags:
          $ref: "#/components/schemas/Tags"
      required:
        - id
        - createAt
        - updateAt
        - email
        - password
        - name
        - mobile
        - cate
        - memos
        - tags
    CreateAccountDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
        mobile:
          type: string
      required:
        - email
        - password
        - name
        - mobile
    CoreOutput:
      type: object
      properties:
        error:
          type: string
        target:
          type: string
        message:
          type: string
        success:
          type: boolean
      required:
        - success
    UpdateAccountDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
        mobile:
          type: string
      required:
        - email
        - name
        - mobile
    LoginInput:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    LoginOutput:
      type: object
      properties:
        error:
          type: string
        target:
          type: string
        message:
          type: string
        success:
          type: boolean
        user:
          $ref: "#/components/schemas/User"
        accessToken:
          type: string
      required:
        - success
    AccessTokenOutput:
      type: object
      properties:
        error:
          type: string
        target:
          type: string
        message:
          type: string
        success:
          type: boolean
        accessToken:
          type: string
      required:
        - success
    CreateMemoInputDto:
      type: object
      properties:
        cateId:
          type: number
          nullable: true
        title:
          type: string
        content:
          type: string
        important:
          type: boolean
        tags:
          type: array
          items:
            type: string
      required:
        - cateId
        - title
        - content
        - important
    CreateCateDto:
      type: object
      properties:
        cateName:
          type: string
      required:
        - cateName
    CateInputDto:
      type: object
      properties:
        cateId:
          type: number
        cateName:
          type: string
      required:
        - cateId
        - cateName
    CreateCateOutputDto:
      type: object
      properties:
        error:
          type: string
        target:
          type: string
        message:
          type: string
        success:
          type: boolean
        cate:
          $ref: "#/components/schemas/Categories"
        savedCate:
          $ref: "#/components/schemas/CateInputDto"
      required:
        - success
        - savedCate
    SendContentDataOutputDto:
      type: object
      properties:
        error:
          type: string
        target:
          type: string
        message:
          type: string
        success:
          type: boolean
        cate:
          $ref: "#/components/schemas/Categories"
        memos:
          $ref: "#/components/schemas/Memos"
        tags:
          $ref: "#/components/schemas/Tags"
      required:
        - success
    UpdateManyCateInputDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/CateInputDto"
      required:
        - data
    CateIdInputDto:
      type: object
      properties:
        cateId:
          type: number
          nullable: true
      required:
        - cateId
    CreateCompletionInputObj:
      type: object
      properties:
        role:
          type: string
        content:
          type: string
      required:
        - role
        - content
    CreateCompletionInputDto:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/CreateCompletionInputObj"
      required:
        - data
