/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AsideDataOutput } from '../models';
// @ts-ignore
import { CateIdInput } from '../models';
// @ts-ignore
import { CateInput } from '../models';
// @ts-ignore
import { CoreOutput } from '../models';
// @ts-ignore
import { CreateCateInput } from '../models';
// @ts-ignore
import { CreateCateOutput } from '../models';
// @ts-ignore
import { CreateMemoInput } from '../models';
// @ts-ignore
import { CreateMemoOutput } from '../models';
// @ts-ignore
import { GetMemosInput } from '../models';
// @ts-ignore
import { GetMemosOutput } from '../models';
// @ts-ignore
import { GetOneMemoOutput } from '../models';
// @ts-ignore
import { ImportantMemoLengthOutput } from '../models';
// @ts-ignore
import { MemoIdInput } from '../models';
// @ts-ignore
import { UpdateMemoInput } from '../models';
/**
 * MemoApi - axios parameter creator
 * @export
 */
export const MemoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {MemoIdInput} memoIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeImportant: async (memoIdInput: MemoIdInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memoIdInput' is not null or undefined
            assertParamExists('changeImportant', 'memoIdInput', memoIdInput)
            const localVarPath = `/memo/changeImportant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(memoIdInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateMemoInput} createMemoInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createMemoInput: CreateMemoInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createMemoInput' is not null or undefined
            assertParamExists('create', 'createMemoInput', createMemoInput)
            const localVarPath = `/memo/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMemoInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateCateInput} createCateInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCate: async (createCateInput: CreateCateInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCateInput' is not null or undefined
            assertParamExists('createCate', 'createCateInput', createCateInput)
            const localVarPath = `/memo/createCate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCateInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CateIdInput} cateIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCate: async (cateIdInput: CateIdInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cateIdInput' is not null or undefined
            assertParamExists('deleteCate', 'cateIdInput', cateIdInput)
            const localVarPath = `/memo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cateIdInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {GetMemosInput} getMemosInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (getMemosInput: GetMemosInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getMemosInput' is not null or undefined
            assertParamExists('get', 'getMemosInput', getMemosInput)
            const localVarPath = `/memo/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getMemosInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAsideData: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/memo/sendContentData`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {MemoIdInput} memoIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOne: async (memoIdInput: MemoIdInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'memoIdInput' is not null or undefined
            assertParamExists('getOne', 'memoIdInput', memoIdInput)
            const localVarPath = `/memo/getOne`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(memoIdInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateMemoInput} updateMemoInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (updateMemoInput: UpdateMemoInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateMemoInput' is not null or undefined
            assertParamExists('update', 'updateMemoInput', updateMemoInput)
            const localVarPath = `/memo/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateMemoInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CateInput} cateInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCategory: async (cateInput: CateInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cateInput' is not null or undefined
            assertParamExists('updateCategory', 'cateInput', cateInput)
            const localVarPath = `/memo/updateOneCate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cateInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MemoApi - functional programming interface
 * @export
 */
export const MemoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MemoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {MemoIdInput} memoIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changeImportant(memoIdInput: MemoIdInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportantMemoLengthOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changeImportant(memoIdInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {CreateMemoInput} createMemoInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(createMemoInput: CreateMemoInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateMemoOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(createMemoInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {CreateCateInput} createCateInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCate(createCateInput: CreateCateInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateCateOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCate(createCateInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {CateIdInput} cateIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCate(cateIdInput: CateIdInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportantMemoLengthOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCate(cateIdInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {GetMemosInput} getMemosInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(getMemosInput: GetMemosInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMemosOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(getMemosInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAsideData(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsideDataOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAsideData(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {MemoIdInput} memoIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOne(memoIdInput: MemoIdInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetOneMemoOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOne(memoIdInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {UpdateMemoInput} updateMemoInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(updateMemoInput: UpdateMemoInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoreOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(updateMemoInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {CateInput} cateInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCategory(cateInput: CateInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoreOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCategory(cateInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MemoApi - factory interface
 * @export
 */
export const MemoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MemoApiFp(configuration)
    return {
        /**
         * 
         * @param {MemoIdInput} memoIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeImportant(memoIdInput: MemoIdInput, options?: any): AxiosPromise<ImportantMemoLengthOutput> {
            return localVarFp.changeImportant(memoIdInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateMemoInput} createMemoInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(createMemoInput: CreateMemoInput, options?: any): AxiosPromise<CreateMemoOutput> {
            return localVarFp.create(createMemoInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateCateInput} createCateInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCate(createCateInput: CreateCateInput, options?: any): AxiosPromise<CreateCateOutput> {
            return localVarFp.createCate(createCateInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CateIdInput} cateIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCate(cateIdInput: CateIdInput, options?: any): AxiosPromise<ImportantMemoLengthOutput> {
            return localVarFp.deleteCate(cateIdInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GetMemosInput} getMemosInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(getMemosInput: GetMemosInput, options?: any): AxiosPromise<GetMemosOutput> {
            return localVarFp.get(getMemosInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAsideData(options?: any): AxiosPromise<AsideDataOutput> {
            return localVarFp.getAsideData(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {MemoIdInput} memoIdInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOne(memoIdInput: MemoIdInput, options?: any): AxiosPromise<GetOneMemoOutput> {
            return localVarFp.getOne(memoIdInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateMemoInput} updateMemoInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(updateMemoInput: UpdateMemoInput, options?: any): AxiosPromise<CoreOutput> {
            return localVarFp.update(updateMemoInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CateInput} cateInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCategory(cateInput: CateInput, options?: any): AxiosPromise<CoreOutput> {
            return localVarFp.updateCategory(cateInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MemoApi - object-oriented interface
 * @export
 * @class MemoApi
 * @extends {BaseAPI}
 */
export class MemoApi extends BaseAPI {
    /**
     * 
     * @param {MemoIdInput} memoIdInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public changeImportant(memoIdInput: MemoIdInput, options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).changeImportant(memoIdInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateMemoInput} createMemoInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public create(createMemoInput: CreateMemoInput, options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).create(createMemoInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateCateInput} createCateInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public createCate(createCateInput: CreateCateInput, options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).createCate(createCateInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CateIdInput} cateIdInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public deleteCate(cateIdInput: CateIdInput, options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).deleteCate(cateIdInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {GetMemosInput} getMemosInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public get(getMemosInput: GetMemosInput, options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).get(getMemosInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public getAsideData(options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).getAsideData(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {MemoIdInput} memoIdInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public getOne(memoIdInput: MemoIdInput, options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).getOne(memoIdInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateMemoInput} updateMemoInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public update(updateMemoInput: UpdateMemoInput, options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).update(updateMemoInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CateInput} cateInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoApi
     */
    public updateCategory(cateInput: CateInput, options?: AxiosRequestConfig) {
        return MemoApiFp(this.configuration).updateCategory(cateInput, options).then((request) => request(this.axios, this.basePath));
    }
}
