/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateCompletionInputDto } from '../models';
/**
 * OpenAiApi - axios parameter creator
 * @export
 */
export const OpenAiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateCompletionInputDto} createCompletionInputDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCompletion: async (createCompletionInputDto: CreateCompletionInputDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCompletionInputDto' is not null or undefined
            assertParamExists('createCompletion', 'createCompletionInputDto', createCompletionInputDto)
            const localVarPath = `/openAi/createCompletion`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCompletionInputDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenAiApi - functional programming interface
 * @export
 */
export const OpenAiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OpenAiApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateCompletionInputDto} createCompletionInputDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCompletion(createCompletionInputDto: CreateCompletionInputDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCompletion(createCompletionInputDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OpenAiApi - factory interface
 * @export
 */
export const OpenAiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OpenAiApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateCompletionInputDto} createCompletionInputDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCompletion(createCompletionInputDto: CreateCompletionInputDto, options?: any): AxiosPromise<object> {
            return localVarFp.createCompletion(createCompletionInputDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OpenAiApi - object-oriented interface
 * @export
 * @class OpenAiApi
 * @extends {BaseAPI}
 */
export class OpenAiApi extends BaseAPI {
    /**
     * 
     * @param {CreateCompletionInputDto} createCompletionInputDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenAiApi
     */
    public createCompletion(createCompletionInputDto: CreateCompletionInputDto, options?: AxiosRequestConfig) {
        return OpenAiApiFp(this.configuration).createCompletion(createCompletionInputDto, options).then((request) => request(this.axios, this.basePath));
    }
}
